CREATE DATABASE heaup_db;
USE heaup_db;
CREATE TABLE stores (id INTEGER NOT NULL AUTO_INCREMENT, name VARCHAR(50) NOT NULL, mail VARCHAR(50) NOT NULL, password VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME, PRIMARY KEY(id));